apiVersion: v1
kind: Secret
metadata:
  name: core-service-secret
type: Opaque
stringData:
  ConnectionStrings__CoreDb: "Host=host.minikube.internal;Port=5433;Database=coredb;Username=postgres;Password=postgres"