apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
type: Opaque
stringData:
  ConnectionStrings__NotificationsDb: "Host=host.minikube.internal;Port=5435;Database=notificationsdb;Username=postgres;Password=postgres"