apiVersion: v1
kind: Secret
metadata:
  name: workflow-service-secret
type: Opaque
stringData:
  ConnectionStrings__WorkflowDb: "Host=host.minikube.internal;Port=5436;Database=workflowdb;Username=postgres;Password=postgres"