apiVersion: v1
kind: Secret
metadata:
  name: users-service-secret
type: Opaque
stringData:
  ConnectionStrings__UsersDb: "Host=host.minikube.internal;Port=5434;Database=usersdb;Username=postgres;Password=postgres"